package kr.re.etri.batis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class EnergyUnitPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.adapt_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date adaptStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String energyTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.adapt_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date adaptEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.base_value
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private BigDecimal baseValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.unit_price
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_unit_price.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.adapt_start_date
     *
     * @return the value of energy_unit_price.adapt_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getAdaptStartDate() {
        return adaptStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.adapt_start_date
     *
     * @param adaptStartDate the value for energy_unit_price.adapt_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setAdaptStartDate(Date adaptStartDate) {
        this.adaptStartDate = adaptStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.energy_type_id
     *
     * @return the value of energy_unit_price.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEnergyTypeId() {
        return energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.energy_type_id
     *
     * @param energyTypeId the value for energy_unit_price.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEnergyTypeId(String energyTypeId) {
        this.energyTypeId = energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.adapt_end_date
     *
     * @return the value of energy_unit_price.adapt_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getAdaptEndDate() {
        return adaptEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.adapt_end_date
     *
     * @param adaptEndDate the value for energy_unit_price.adapt_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setAdaptEndDate(Date adaptEndDate) {
        this.adaptEndDate = adaptEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.base_value
     *
     * @return the value of energy_unit_price.base_value
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public BigDecimal getBaseValue() {
        return baseValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.base_value
     *
     * @param baseValue the value for energy_unit_price.base_value
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setBaseValue(BigDecimal baseValue) {
        this.baseValue = baseValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.unit_id
     *
     * @return the value of energy_unit_price.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.unit_id
     *
     * @param unitId the value for energy_unit_price.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.unit_price
     *
     * @return the value of energy_unit_price.unit_price
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.unit_price
     *
     * @param unitPrice the value for energy_unit_price.unit_price
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.created_at
     *
     * @return the value of energy_unit_price.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.created_at
     *
     * @param createdAt the value for energy_unit_price.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.created_by
     *
     * @return the value of energy_unit_price.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.created_by
     *
     * @param createdBy the value for energy_unit_price.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.updated_at
     *
     * @return the value of energy_unit_price.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.updated_at
     *
     * @param updatedAt the value for energy_unit_price.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_unit_price.updated_by
     *
     * @return the value of energy_unit_price.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_unit_price.updated_by
     *
     * @param updatedBy the value for energy_unit_price.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}