package kr.re.etri.batis.domain;

import java.util.Date;

public class EnergyGoal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.goal_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date goalStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.goal_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date goalEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String energyTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.goal_value
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Integer goalValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.update_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_goal.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.goal_start_date
     *
     * @return the value of energy_goal.goal_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getGoalStartDate() {
        return goalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.goal_start_date
     *
     * @param goalStartDate the value for energy_goal.goal_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setGoalStartDate(Date goalStartDate) {
        this.goalStartDate = goalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.goal_end_date
     *
     * @return the value of energy_goal.goal_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getGoalEndDate() {
        return goalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.goal_end_date
     *
     * @param goalEndDate the value for energy_goal.goal_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setGoalEndDate(Date goalEndDate) {
        this.goalEndDate = goalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.energy_type_id
     *
     * @return the value of energy_goal.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEnergyTypeId() {
        return energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.energy_type_id
     *
     * @param energyTypeId the value for energy_goal.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEnergyTypeId(String energyTypeId) {
        this.energyTypeId = energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.goal_value
     *
     * @return the value of energy_goal.goal_value
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Integer getGoalValue() {
        return goalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.goal_value
     *
     * @param goalValue the value for energy_goal.goal_value
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setGoalValue(Integer goalValue) {
        this.goalValue = goalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.unit_id
     *
     * @return the value of energy_goal.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.unit_id
     *
     * @param unitId the value for energy_goal.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.created_at
     *
     * @return the value of energy_goal.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.created_at
     *
     * @param createdAt the value for energy_goal.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.created_by
     *
     * @return the value of energy_goal.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.created_by
     *
     * @param createdBy the value for energy_goal.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.update_at
     *
     * @return the value of energy_goal.update_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.update_at
     *
     * @param updateAt the value for energy_goal.update_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_goal.updated_by
     *
     * @return the value of energy_goal.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_goal.updated_by
     *
     * @param updatedBy the value for energy_goal.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}