package kr.re.etri.batis.domain;

import java.util.Date;

public class EnergyType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String energyTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.energy_type_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String energyTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column energy_type.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.energy_type_id
     *
     * @return the value of energy_type.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEnergyTypeId() {
        return energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.energy_type_id
     *
     * @param energyTypeId the value for energy_type.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEnergyTypeId(String energyTypeId) {
        this.energyTypeId = energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.energy_type_name
     *
     * @return the value of energy_type.energy_type_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEnergyTypeName() {
        return energyTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.energy_type_name
     *
     * @param energyTypeName the value for energy_type.energy_type_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEnergyTypeName(String energyTypeName) {
        this.energyTypeName = energyTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.unit_id
     *
     * @return the value of energy_type.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.unit_id
     *
     * @param unitId the value for energy_type.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.created_at
     *
     * @return the value of energy_type.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.created_at
     *
     * @param createdAt the value for energy_type.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.created_by
     *
     * @return the value of energy_type.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.created_by
     *
     * @param createdBy the value for energy_type.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.updated_at
     *
     * @return the value of energy_type.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.updated_at
     *
     * @param updatedAt the value for energy_type.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column energy_type.updated_by
     *
     * @return the value of energy_type.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column energy_type.updated_by
     *
     * @param updatedBy the value for energy_type.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}