package kr.re.etri.batis.domain;

import java.util.Date;

public class FactoryEquipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.equipment_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String equipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.equipment_position
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String equipmentPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.equpment_install_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date equpmentInstallDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.equpment_repair_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date equpmentRepairDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_equipment.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.equipment_id
     *
     * @return the value of factory_equipment.equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.equipment_id
     *
     * @param equipmentId the value for factory_equipment.equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.equipment_name
     *
     * @return the value of factory_equipment.equipment_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.equipment_name
     *
     * @param equipmentName the value for factory_equipment.equipment_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.equipment_position
     *
     * @return the value of factory_equipment.equipment_position
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEquipmentPosition() {
        return equipmentPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.equipment_position
     *
     * @param equipmentPosition the value for factory_equipment.equipment_position
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEquipmentPosition(String equipmentPosition) {
        this.equipmentPosition = equipmentPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.equpment_install_date
     *
     * @return the value of factory_equipment.equpment_install_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getEqupmentInstallDate() {
        return equpmentInstallDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.equpment_install_date
     *
     * @param equpmentInstallDate the value for factory_equipment.equpment_install_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEqupmentInstallDate(Date equpmentInstallDate) {
        this.equpmentInstallDate = equpmentInstallDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.equpment_repair_date
     *
     * @return the value of factory_equipment.equpment_repair_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getEqupmentRepairDate() {
        return equpmentRepairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.equpment_repair_date
     *
     * @param equpmentRepairDate the value for factory_equipment.equpment_repair_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEqupmentRepairDate(Date equpmentRepairDate) {
        this.equpmentRepairDate = equpmentRepairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.created_at
     *
     * @return the value of factory_equipment.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.created_at
     *
     * @param createdAt the value for factory_equipment.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.created_by
     *
     * @return the value of factory_equipment.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.created_by
     *
     * @param createdBy the value for factory_equipment.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.updated_at
     *
     * @return the value of factory_equipment.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.updated_at
     *
     * @param updatedAt the value for factory_equipment.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_equipment.updated_by
     *
     * @return the value of factory_equipment.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_equipment.updated_by
     *
     * @param updatedBy the value for factory_equipment.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}