package kr.re.etri.batis.domain;

import java.util.Date;

public class PlanProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_process.product_plan_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String productPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_process.process_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_process.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_process.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_process.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_process.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_process.product_plan_id
     *
     * @return the value of plan_process.product_plan_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProductPlanId() {
        return productPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_process.product_plan_id
     *
     * @param productPlanId the value for plan_process.product_plan_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProductPlanId(String productPlanId) {
        this.productPlanId = productPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_process.process_id
     *
     * @return the value of plan_process.process_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_process.process_id
     *
     * @param processId the value for plan_process.process_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_process.created_at
     *
     * @return the value of plan_process.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_process.created_at
     *
     * @param createdAt the value for plan_process.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_process.created_by
     *
     * @return the value of plan_process.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_process.created_by
     *
     * @param createdBy the value for plan_process.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_process.updated_at
     *
     * @return the value of plan_process.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_process.updated_at
     *
     * @param updatedAt the value for plan_process.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_process.updated_by
     *
     * @return the value of plan_process.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_process.updated_by
     *
     * @param updatedBy the value for plan_process.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}