package kr.re.etri.batis.domain;

import java.util.Date;

public class Process {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String processName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date processStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String processEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_type
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String processType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.factory_equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String factoryEquipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_status
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String processStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.product_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_id
     *
     * @return the value of process.process_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_id
     *
     * @param processId the value for process.process_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_name
     *
     * @return the value of process.process_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_name
     *
     * @param processName the value for process.process_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessName(String processName) {
        this.processName = processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_start_date
     *
     * @return the value of process.process_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getProcessStartDate() {
        return processStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_start_date
     *
     * @param processStartDate the value for process.process_start_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessStartDate(Date processStartDate) {
        this.processStartDate = processStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_end_date
     *
     * @return the value of process.process_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProcessEndDate() {
        return processEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_end_date
     *
     * @param processEndDate the value for process.process_end_date
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessEndDate(String processEndDate) {
        this.processEndDate = processEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_type
     *
     * @return the value of process.process_type
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_type
     *
     * @param processType the value for process.process_type
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessType(String processType) {
        this.processType = processType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.factory_equipment_id
     *
     * @return the value of process.factory_equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getFactoryEquipmentId() {
        return factoryEquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.factory_equipment_id
     *
     * @param factoryEquipmentId the value for process.factory_equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setFactoryEquipmentId(String factoryEquipmentId) {
        this.factoryEquipmentId = factoryEquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_status
     *
     * @return the value of process.process_status
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_status
     *
     * @param processStatus the value for process.process_status
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.created_at
     *
     * @return the value of process.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.created_at
     *
     * @param createdAt the value for process.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.created_by
     *
     * @return the value of process.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.created_by
     *
     * @param createdBy the value for process.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.updated_at
     *
     * @return the value of process.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.updated_at
     *
     * @param updatedAt the value for process.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.updated_by
     *
     * @return the value of process.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.updated_by
     *
     * @param updatedBy the value for process.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.product_id
     *
     * @return the value of process.product_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.product_id
     *
     * @param productId the value for process.product_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}