package kr.re.etri.batis.domain;

import java.util.Date;

public class ProductType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.product_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String productTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.product_type_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String productTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.product_type_id
     *
     * @return the value of product_type.product_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.product_type_id
     *
     * @param productTypeId the value for product_type.product_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProductTypeId(String productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.product_type_name
     *
     * @return the value of product_type.product_type_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.product_type_name
     *
     * @param productTypeName the value for product_type.product_type_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.created_at
     *
     * @return the value of product_type.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.created_at
     *
     * @param createdAt the value for product_type.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.created_by
     *
     * @return the value of product_type.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.created_by
     *
     * @param createdBy the value for product_type.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.updated_at
     *
     * @return the value of product_type.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.updated_at
     *
     * @param updatedAt the value for product_type.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.updated_by
     *
     * @return the value of product_type.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.updated_by
     *
     * @param updatedBy the value for product_type.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}