package kr.re.etri.batis.domain;

import java.util.Date;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_type
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String tagType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_desc
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String tagDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String energyTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_id
     *
     * @return the value of tag.tag_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_id
     *
     * @param tagId the value for tag.tag_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_type
     *
     * @return the value of tag.tag_type
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getTagType() {
        return tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_type
     *
     * @param tagType the value for tag.tag_type
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_desc
     *
     * @return the value of tag.tag_desc
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getTagDesc() {
        return tagDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_desc
     *
     * @param tagDesc the value for tag.tag_desc
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setTagDesc(String tagDesc) {
        this.tagDesc = tagDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.equipment_id
     *
     * @return the value of tag.equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.equipment_id
     *
     * @param equipmentId the value for tag.equipment_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.unit_id
     *
     * @return the value of tag.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.unit_id
     *
     * @param unitId the value for tag.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.energy_type_id
     *
     * @return the value of tag.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getEnergyTypeId() {
        return energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.energy_type_id
     *
     * @param energyTypeId the value for tag.energy_type_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setEnergyTypeId(String energyTypeId) {
        this.energyTypeId = energyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.created_at
     *
     * @return the value of tag.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.created_at
     *
     * @param createdAt the value for tag.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.created_by
     *
     * @return the value of tag.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.created_by
     *
     * @param createdBy the value for tag.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.updated_at
     *
     * @return the value of tag.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.updated_at
     *
     * @param updatedAt the value for tag.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.updated_by
     *
     * @return the value of tag.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.updated_by
     *
     * @param updatedBy the value for tag.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}