package kr.re.etri.batis.domain;

import java.util.Date;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.unit_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_id
     *
     * @return the value of unit.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_id
     *
     * @param unitId the value for unit.unit_id
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.unit_name
     *
     * @return the value of unit.unit_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.unit_name
     *
     * @param unitName the value for unit.unit_name
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.created_at
     *
     * @return the value of unit.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.created_at
     *
     * @param createdAt the value for unit.created_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.created_by
     *
     * @return the value of unit.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.created_by
     *
     * @param createdBy the value for unit.created_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.updated_at
     *
     * @return the value of unit.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.updated_at
     *
     * @param updatedAt the value for unit.updated_at
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.updated_by
     *
     * @return the value of unit.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.updated_by
     *
     * @param updatedBy the value for unit.updated_by
     *
     * @mbg.generated Wed Apr 20 10:37:21 KST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}