package kr.re.etri.batis.mapper;

import java.util.Date;
import java.util.List;
import kr.re.etri.batis.domain.EnergyUnitPrice;
import org.apache.ibatis.annotations.Param;

public interface EnergyUnitPriceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_unit_price
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(@Param("adaptStartDate") Date adaptStartDate, @Param("energyTypeId") String energyTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_unit_price
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(EnergyUnitPrice row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_unit_price
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	EnergyUnitPrice selectByPrimaryKey(@Param("adaptStartDate") Date adaptStartDate,
			@Param("energyTypeId") String energyTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_unit_price
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<EnergyUnitPrice> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_unit_price
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(EnergyUnitPrice row);
}