package kr.re.etri.batis.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import kr.re.etri.batis.domain.EnergyUsage;
import org.apache.ibatis.annotations.Param;

public interface EnergyUsageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_usage
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(@Param("measureDate") Date measureDate, @Param("tagId") String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_usage
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(EnergyUsage row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_usage
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	EnergyUsage selectByPrimaryKey(@Param("measureDate") Date measureDate, @Param("tagId") String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_usage
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<EnergyUsage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table energy_usage
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(EnergyUsage row);

	
	Map<String, Object> selectEnergyUsageCost(@Param("tagEnergyType") String tagEnergyType);
	Map<String, Object> selectEnergyUsageCostTotal(@Param("tagEnergyType") String tagEnergyType);
	Map<String, Object> selectEnergyUsage(@Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo, @Param("tagEnergyType") String tagEnergyType);
	Map<String, Object> selectEnergyUsageMax(@Param("tagTo") String tagTo, @Param("tagEnergyType") String tagEnergyType);
}