package kr.re.etri.batis.mapper;

import java.util.List;
import java.util.Map;

import kr.re.etri.batis.domain.FactoryEquipment;

public interface FactoryEquipmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory_equipment
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String equipmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory_equipment
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(FactoryEquipment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory_equipment
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	FactoryEquipment selectByPrimaryKey(String equipmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory_equipment
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<FactoryEquipment> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table factory_equipment
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(FactoryEquipment row);
	
	List<Map<String, String>> selectNowEquipmentWorker();
}