package kr.re.etri.batis.mapper;

import java.util.List;
import kr.re.etri.batis.domain.PlanProcess;
import org.apache.ibatis.annotations.Param;

public interface PlanProcessMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plan_process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(@Param("productPlanId") String productPlanId, @Param("processId") String processId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plan_process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(PlanProcess row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plan_process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	PlanProcess selectByPrimaryKey(@Param("productPlanId") String productPlanId, @Param("processId") String processId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plan_process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<PlanProcess> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plan_process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(PlanProcess row);
}