package kr.re.etri.batis.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import kr.re.etri.batis.domain.Process;

public interface ProcessMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String processId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(Process row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	Process selectByPrimaryKey(String processId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<Process> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table process
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(Process row);
	

	List<Map<String, String>> selectChangeTime();
}