package kr.re.etri.batis.mapper;

import java.util.List;
import kr.re.etri.batis.domain.Product;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	Product selectByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<Product> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(Product row);
}