package kr.re.etri.batis.mapper;

import java.util.List;
import kr.re.etri.batis.domain.ProductType;

public interface ProductTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String productTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(ProductType row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	ProductType selectByPrimaryKey(String productTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<ProductType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(ProductType row);
}