package kr.re.etri.batis.mapper;

import java.util.List;
import java.util.Map;

import kr.re.etri.batis.domain.ProductPlan;

public interface ProductPlanMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_plan
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String productPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_plan
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(ProductPlan row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_plan
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	ProductPlan selectByPrimaryKey(String productPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_plan
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<ProductPlan> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_plan
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(ProductPlan row);
	
	Map<String, String> selectNowPlan();
	List<Map<String, String>> selectTodayPlan();

	List<Map<String, String>> selectMonthPlanList();
	List<Map<String, String>> selectTodayNowTotalPerProductType(String searchDateType);
	List<Map<String, String>> selectMonthTotalPerProductType(String searchDateType);
	

	List<Map<String, String>> selectToday_Now_Product_Weight();
	List<Map<String, String>> selectToday_Total_Product_Weight();
}