package kr.re.etri.batis.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import kr.re.etri.batis.domain.RawTagDate;
import org.apache.ibatis.annotations.Param;

public interface RawTagDateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table raw_tag_date
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(@Param("measureDate") Date measureDate, @Param("tagId") String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table raw_tag_date
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(RawTagDate row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table raw_tag_date
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	RawTagDate selectByPrimaryKey(@Param("measureDate") Date measureDate, @Param("tagId") String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table raw_tag_date
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<RawTagDate> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table raw_tag_date
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(RawTagDate row);
	
	List<RawTagDate> selectTodayAll(@Param("measureDate") String measureDate, @Param("tagId") String tagId);
	
	List<Map<String, String>> selectPerTime(@Param("tagMinute") Integer tagMinute, @Param("tagId") String tagId, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);

	RawTagDate selectNowData(@Param("tagId") String tagId);

	List<RawTagDate> selectTodayBetween15(@Param("tagId") String tagId);
	List<RawTagDate> selectYesterdayBetween15(@Param("tagId") String tagId);
	
	List<RawTagDate> selectTodayBetween15Total();
	List<RawTagDate> selectYesterdayBetween15Total();
	
	List<Map<String, String>> selectPerDay(@Param("tagId") String tagId, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	List<Map<String, String>> selectPerWeek(@Param("tagId") String tagId, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	List<Map<String, String>> selectPerMonth(@Param("tagId") String tagId, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	List<Map<String, String>> selectPerYear(@Param("tagId") String tagId, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);

	List<Map<String, String>> selectTotalPerDay(@Param("tagId1") String tagId1, @Param("tagId2") String tagId2, @Param("tagId3") String tagId3, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	List<Map<String, String>> selectTotalPerWeek(@Param("tagId1") String tagId1, @Param("tagId2") String tagId2, @Param("tagId3") String tagId3, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	List<Map<String, String>> selectTotalPerMonth(@Param("tagId1") String tagId1, @Param("tagId2") String tagId2, @Param("tagId3") String tagId3, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	List<Map<String, String>> selectTotalPerYear(@Param("tagId1") String tagId1, @Param("tagId2") String tagId2, @Param("tagId3") String tagId3, @Param("tagFrom") String tagFrom, @Param("tagTo") String tagTo);
	
	


}