package kr.re.etri.batis.mapper;

import java.util.List;
import kr.re.etri.batis.domain.Tag;

public interface TagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(Tag row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	Tag selectByPrimaryKey(String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<Tag> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(Tag row);
}