package kr.re.etri.batis.mapper;

import java.util.List;
import kr.re.etri.batis.domain.Worker;

public interface WorkerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int deleteByPrimaryKey(String workerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int insert(Worker row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	Worker selectByPrimaryKey(String workerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	List<Worker> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Wed Apr 20 10:51:28 KST 2022
	 */
	int updateByPrimaryKey(Worker row);
}